# src/constants.py
class Constants:
    # Ekran ayarları
    SCREEN_SCALE = "SCREEN_SCALE"
    DEFAULT_SCREEN_SCALE = 8
    SCREEN_WIDTH = 160
    SCREEN_HEIGHT = 114
    DISPLAY_OFFSET_X = 4
    DISPLAY_OFFSET_Y = 7

    # Kamera
    CAMERA_SHAKE = "CAMERA_SHAKE"
    DEFAULT_CAMERA_SHAKE = False

    # Oyuncu ayarları
    PLAYER_MAX_LIVES = "PLAYER_MAX_LIVES"
    DEFAULT_PLAYER_MAX_LIVES = 2
    PLAYER_SPEED = "PLAYER_SPEED"
    DEFAULT_PLAYER_SPEED = 40
    PLAYER_ANIMATION_SPEED = "PLAYER_ANIMATION_SPEED"
    DEFAULT_PLAYER_ANIMATION_SPEED = 40
    PLAYER_BULLET_SPEED = "PLAYER_BULLET_SPEED"
    DEFAULT_PLAYER_BULLET_SPEED = 50
    PLAYER_TIME_IN_CAGE = "PLAYER_TIME_IN_CAGE"
    DEFAULT_PLAYER_TIME_IN_CAGE = 15.0

    # Düşman ayarları
    BURWARS = "BURWARS"
    DEFAULT_BURWARS = 6
    GARWORS_PER_LEVEL = "GARWORS_PER_LEVEL"
    DEFAULT_GARWORS_PER_LEVEL = 1
    THORWORS_PER_LEVEL = "THORWORS_PER_LEVEL"
    DEFAULT_THORWORS_PER_LEVEL = 1
    ENEMY_SPEED_1 = "ENEMY_SPEED_1"
    DEFAULT_ENEMY_SPEED_1 = 20.0
    ENEMY_SPEED_2 = "ENEMY_SPEED_2"
    DEFAULT_ENEMY_SPEED_2 = 30.0
    ENEMY_SPEED_3 = "ENEMY_SPEED_3"
    DEFAULT_ENEMY_SPEED_3 = 40.0
    ENEMY_SPEED_4 = "ENEMY_SPEED_4"
    DEFAULT_ENEMY_SPEED_4 = 50.0
    ENEMY_SPEED_5 = "ENEMY_SPEED_5"
    DEFAULT_ENEMY_SPEED_5 = 60.0
    WORLUK_SPEED = "WORLUK_SPEED"
    DEFAULT_WORLUK_SPEED = 60.0
    WIZARD_SPEED = "WIZARD_SPEED"
    DEFAULT_WIZARD_SPEED = 40.0
    WIZARD_TELEPORT_COOLDOWN = "WIZARD_TELEPORT_COOLDOWN"
    DEFAULT_WIZARD_TELEPORT_COOLDOWN = 1.0
    ENEMY_BULLET_SPEED = "ENEMY_BULLET_SPEED"
    DEFAULT_ENEMY_BULLET_SPEED = 50

    # Skor ayarları
    BURWOR_SCORE = "BURWOR_SCORE"
    DEFAULT_BURWOR_SCORE = 100
    GARWOR_SCORE = "GARWOR_SCORE"
    DEFAULT_GARWOR_SCORE = 200
    THORWOR_SCORE = "THORWOR_SCORE"
    DEFAULT_THORWOR_SCORE = 500
    WORLUK_SCORE = "WORLUK_SCORE"
    DEFAULT_WORLUK_SCORE = 1000
    WIZARD_SCORE = "WIZARD_SCORE"
    DEFAULT_WIZARD_SCORE = 1000
    OTHER_PLAYER_SCORE = "OTHER_PLAYER_SCORE"
    DEFAULT_OTHER_PLAYER_SCORE = 1000
    EXTRA_LIFE_SCORE = "EXTRA_LIFE_SCORE"
    DEFAULT_EXTRA_LIFE_SCORE = 10000
    
    # Oyun düzeyi sabitleri
    LEVEL_KILL_ENEMIES = 0
    LEVEL_WORLUK = 1
    LEVEL_WIZARD = 2
    LEVEL_WORLUK_DEATH = 3
    LEVEL_WIZARD_DEATH = 4
    LEVEL_WORLUK_ESCAPE = 5